### ISSUE TITLE
[BE] Implement multilanguage

### ISSUE THREAD

**Issue by CloudSalander** [IT-Academy-BCN/ita-landing#75]
Catalan by default language, if not specified in the api call
Spanish and catalan.

**Comment by Edvenan** [comment]
1) [**Localization**](https://laravel.com/docs/10.x/localization#configuring-the-locale)

   Laravel's localization features provide a convenient way to retrieve strings in various languages, allowing you to easily support multiple languages within your application.

     This feature has been used to translate validation error messages, user authentication messages and other custom API response messages to the client.
  
     Language strings are stored in files within the application's `/resoruces/lang` directory. Within this directory, there are subdirectories for each language supported by the application ('ca' and 'es'). This is the approach Laravel uses to manage translation strings for built-in Laravel features such as validation error messages.

         /lang
            /en
               messages.php
            /es
               messages.php

      By default, the Laravel application skeleton does not include the lang directory so we have to publish it via the command `php artisan lang:publish`.
   <br>

   **Configuring the API Locale**\
     The default language for the application is stored in the `config/app.php ` configuration file's locale configuration option.\
     `Default locale` is set to `'ca'`\
     `Supported locales` are `'ca', 'es'`\
     `Fallback_locale` is set to `'ca'`, meaning that it will default to 'ca' if the required locale is neither of the supported locales.
   <br>

   **Determining The Current Locale**\
     A middleware called `SetLocale` has been implemented to capture the required locale from the API client's http requests.
     The middleware looks for Header `Accept-Language` in the http request from the client and sets the application locale based on its content. It will default to the Default locale if the required locale is not supported or if the header Accept-Language is not present in the http request.

   **Retrieving Translation Strings**\
   You may retrieve translation strings from your language files using the `__()` helper function, passing the lang file that contains the key and the key itself using "dot" syntax. For example, let's retrieve the 'app_not_found' translation string from the lang/en/api.php language file:

         echo __('api.app_not_found');

      If the specified translation string does not exist, the `__()` function will return the translation string key. So, using the example above, the __ function would return `api.app_not_found` if the translation string does not exist.

   <br>

2) [**Laravel Translatable**](https://docs.astrotomic.info/laravel-translatable/)
   
     This package allows us to store translations of our models (`Apps, Faqs`) into the database while removing the complexity in retrieving and storing multilingual model instances. With this package less code is needed, as the translations are being fetched/saved when you fetch/save your instance.
     A new database table is required for each translatable model so migrations have been updated accordingly.

   **Getting translated attributes**\
    The client does not need to worry about the translation as long as the header Accept_Language is defined in his request.

   Examples:
      - Precondition: header Accept-Language = 'ca', different than the supported locales or not present:
  
             echo $app->title; // La meva aplicació

      - Precondition: header Accept-Language = 'es':
  
             echo $app->title; // Mi aplicación

   **Filling multiple translations**\
    When creating or updating our model instances (`'app', 'faq'`), the client just need to send an array with the translations and the package will do the rest.

   Example:
       
         $data = [
            'ca' => ['title' => 'La meva aplicació', 
                     'description' => 'Tota una obra mestre de l'arquitectura.'],
            'es' => ['title' => 'Mi aplicación', 
                     'description' => 'Toda una obra maestra de la arquitectura.'],
            'url' => 'hhtps://miaplicacion.com',
            'github' => 'https://github.com/user',
            'state' => 'COMPLETE'
            ];

         $app = App::create($data);

   Example of Postman request to create an 'app' model instance and the API response:
<p align='center' >
  <img  alt="league_Auth_user_Teams_mgmt" src='https://github.com/IT-Academy-BCN/ita-landing-backend/assets/97369106/ef2cade3-b015-424e-af2e-5a40fd8f1d7d' width="85%">
</p>

3) **Feature Test**
   
   PHPUnit has been used to test this functionality and test cases can be found in `tests/Feature/MultilanguageTest.php`.


4) **Impact**

   - This feature implies changes in `apps and faqs tables` an their respective migrations have been updated. That means that running these new migrations **will lead to the deletion of existing data in both tables**!! 
  
   - **App and Faq factories should be updated** to generate data in the two supported locales ('ca', 'es'). Such task has not been done as part of this pull request.
  
   - The implementation of this feature has a significant impact on how the client and PHPUnit requests are made when **creating** or **updating** model instances like `apps` or `faqs`.

      Existing Code snippets like

            $app = [
                     'title' => 'El joc de les cadires',
                     'description' => 'Joc amb més d'un jugador que consisteix en...',
                     'url' => 'https:/chairgame.com',
                     'github' => 'https://github.com',
                     'state' => 'COMPLETED'
               ];
               
               $this->withHeaders(['Authorization' => 'Bearer ' . $this->authCreated()])->postJson(route('app.store'), $app);

      will have to be adapted to avoid validation errors.\
      Below the adapted code:

            $app = [
                     'ca' => ['title' => 'El joc de les cadires',
                              'description' => "Joc amb més d'un jugador que consisteix en..."],
                     'es' => ['title' => 'El juego de las sillas',
                              'description' => 'Juego con más de un jugador que consiste en...'],
                     'url' => 'https://chairgame.com',
                     'github' => 'https://github.com',
                     'state' => 'COMPLETED'
               ];
               
               $this->withHeaders(['Authorization' => 'Bearer ' . $this->authCreated()])->postJson(route('app.store'), $app);
   
      That means that **client requests** must be reviewed as well as **Feature Test cases/suites**.

   - The way this feature has been implemented, requires that when **creating** a model instance (`'app'` or `'faq'`), translations for both supported languages `'ca'`and `'es'` must be provided for both attributes `'title'`and `'description'` at creation time. Otherwise, a validation error will be triggered.\
   This is not the case when **updating** since it is allowed to update only one particular attribute in one particular language if required.

   - As a consequence of the above impact, **Swagger** tags must also be adjusted for all those methods with inputs and outputs affected by this feature.
  
   - **Route names** have been added to the existing routes in `Routes/api.php` to facilitate the coding of test cases: `faq.show`, `faq.store` and `faq.update`
