### ISSUE TITLE
[BE] SMTP server config

### ISSUE THREAD

**Issue by vicenlu** [IT-Academy-BCN/ita-landing#84]

**Comment by Edvenan** [comment]
**Benefits of using Gmail's SMTP server**
- Using Gmail's SMTP server helps ensure that emails are not stored in the recipient’s spam fold.
- It is the prominent choice of many users for email communication because of their servers' stability and consistent performance.
- That said, it's important to know that Google imposes some limitations on free accounts, e.g.,, a maximum of 100 emails can be sent per day.

**Setting up Google SMTP server**
>Step 1) Create Google account: ita.landing@gmail.com password: 1Italanding
   
>Step 2) Setup Google Account to allow "More secure App access" under `Security` section:
   1) Enable 2FA
   2) Go to `App passwords` and click on `create`. Assign the given app password to `MAIL_PASSWORD=` in your `.env`file.
   

**Setting up SMTP config in Laravel project**
To Insert the following lines into the  .env file:

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com        # Gmail SMTP server url
MAIL_PORT=465                   # SMTP port authenticated with SSL
MAIL_USERNAME=ita.landing@gmail.com
MAIL_PASSWORD='jhqf jziw iofq efey'
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS="IT.Academy.Landing@barcelonactiva.cat"
MAIL_FROM_NAME="${APP_NAME}"
